import { cn } from "@/lib/utils";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import "react-loading-skeleton/dist/skeleton.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // setting light mode
    <html lang="en" className="light">
      <Providers>
        <body
          // every page should be atleast 100vh - set with min-h-screen
          // antialiased is used for font smoothing
          className={cn("min-h-screen font-sans antialiased", inter.className)}
        >
          <Navbar />
          {children}
        </body>
      </Providers>
    </html>
  );
}
